spring.thymeleaf.cache=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
app.browser-session.auto-shutdown-enabled=${MIHOJA_AUTO_SHUTDOWN_ENABLED:true}
management.endpoint.health.show-details=always
