-- Schema for MiHoja (PostgreSQL / Supabase)

create table if not exists persona (
    n bigint generated by default as identity primary key,
    numero integer,
    nombres varchar(255),
    apellidos varchar(255),
    cedula varchar(255) unique,
    lugar_expedicion varchar(255),
    fecha_nacimiento date,
    direccion varchar(255),
    sexo varchar(255),
    correo_institucional varchar(255),
    telefono_institucional varchar(255),
    enlace_sigep varchar(255),
    estado varchar(255),
    numero_hijos integer,
    imagen_url varchar(255)
);

create table if not exists cargo_laboral (
    id_cargo bigint generated by default as identity primary key,
    cargo varchar(255),
    codigo varchar(255),
    dependencia varchar(255)
);

create table if not exists alergia (
    id_alergia bigint generated by default as identity primary key,
    nombre varchar(255) not null,
    n bigint not null references persona(n)
);

create table if not exists contacto_emergencia (
    id_contacto bigint generated by default as identity primary key,
    nombre_contacto_emergencia varchar(255),
    parentesco varchar(255),
    telefono_contacto_emergencia varchar(255),
    n bigint not null references persona(n)
);

create table if not exists enfermedad (
    id_enfermedad bigint generated by default as identity primary key,
    nombre varchar(255) not null,
    n bigint not null references persona(n)
);

create table if not exists formacion (
    id_formacion bigint generated by default as identity primary key,
    formacion_academica varchar(255),
    grado varchar(255),
    titulo varchar(255),
    n bigint not null references persona(n)
);

create table if not exists medicamento (
    id_medicamento bigint generated by default as identity primary key,
    nombre varchar(255) not null,
    n bigint not null references persona(n)
);

create table if not exists persona_cargo_laboral (
    id_pcl bigint generated by default as identity primary key,
    persona_id bigint not null references persona(n),
    cargo_id bigint not null references cargo_laboral(id_cargo),
    fecha_ingreso date,
    fecha_firma_contrato date,
    meses_experiencia integer
);

create table if not exists induccion_examen (
    id_induccion bigint generated by default as identity primary key,
    induccion boolean,
    examen_ingreso boolean,
    fecha_egreso date,
    persona_cargo_id bigint not null references persona_cargo_laboral(id_pcl)
);

create table if not exists riesgo_procedencia (
    id_riesgo bigint generated by default as identity primary key,
    riesgo varchar(255),
    medio_transporte varchar(255),
    procedencia_trabajador varchar(255),
    n bigint references persona(n)
);

create table if not exists salud (
    id_salud bigint generated by default as identity primary key,
    dotacion varchar(255),
    arl varchar(255),
    eps varchar(255),
    afp varchar(255),
    ccf varchar(255),
    rh varchar(255),
    carnet_vacunacion boolean,
    n bigint references persona(n)
);

create table if not exists enfermedad_medicamento (
    enfermedad_id bigint not null references enfermedad(id_enfermedad),
    medicamento_id bigint not null references medicamento(id_medicamento),
    primary key (enfermedad_id, medicamento_id)
);

create index if not exists idx_alergia_n on alergia(n);
create index if not exists idx_contacto_emergencia_n on contacto_emergencia(n);
create index if not exists idx_enfermedad_n on enfermedad(n);
create index if not exists idx_formacion_n on formacion(n);
create index if not exists idx_medicamento_n on medicamento(n);
create index if not exists idx_persona_cargo_laboral_persona_id on persona_cargo_laboral(persona_id);
create index if not exists idx_persona_cargo_laboral_cargo_id on persona_cargo_laboral(cargo_id);
create index if not exists idx_induccion_examen_persona_cargo_id on induccion_examen(persona_cargo_id);
create index if not exists idx_riesgo_procedencia_n on riesgo_procedencia(n);
create index if not exists idx_salud_n on salud(n);
